Try to extract the error message from error.cause.message
We get
ErrorWithCause: Error while iterating over SSE stream
Caused by:
Error: Error received from the server.
{"request_id": ...,"code":400,"message":...}

Which is unfortunately a mix of test and json and not nice for
extracting the proper error message from the server.