Don't throw an exception if deleting a directory fail.
The external diff view provider throws an error while reverting the diff if the directory is missing. This is not a real error though, we should continue the revert even if deleting the directories failed.

Fixes:

```
[2025-08-27T22:52:23.673] #bot.cline.server.ts ProtoBus handler error: /cline.TaskService/clearTask
Error: ENOENT: no such file or directory, rmdir '/Users/sjf/plugin/.github/actions/build-test-upload'
    at async Object.rmdir (node:internal/fs/promises:818:10)
    at async ExternalDiffViewProvider.revertChanges (/path/to/cline/core/0.0.1/cline-core.js:848418:9)
    at async Task.abortTask (/path/to/cline/core/0.0.1/cline-core.js:830605:9)
    at async Controller.clearTask (/path/to/cline/core/0.0.1/cline-core.js:832296:9)
    at async clearTask (/path/to/cline/core/0.0.1/cline-core.js:658823:3)
    at async Object.clearTask (/path/to/cline/core/0.0.1/cline-core.js:872829:23)
  ```